spring.application.name=service-b

server.servlet.context-path=/b

spring.datasource.url=jdbc:postgresql://postgres:5432/task_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=archiuser
spring.datasource.password=archipass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
