spring.application.name=archi

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT secret (clé 256 bits, base64)
jwt.secret=VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1leGFtcGxlLWtleS1mb3ItanVzdC1mb3ItZGVtbw==

# Log level for full debug (affiche tout, y compris hash password)
logging.level.com.softwarearchi.archi=DEBUG

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Application MQ settings
app.mq.exchange=auth.events
app.mq.rk.userRegistered=auth.user-registered
app.mq.rk.emailVerified=auth.email-verified

# Mail (MailHog) Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
